<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        DB::statement('CREATE TABLE `house_projects` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `project_id` varchar(255) DEFAULT NULL,
  `project_name` varchar(255) DEFAULT NULL,
  `sponsor` varchar(255) DEFAULT NULL,
  `project_spec` text DEFAULT NULL,
  `agency_project_no` varchar(255) DEFAULT NULL,
  `donor_id` bigint(20) unsigned DEFAULT NULL,
  `project_manager_id` bigint(20) unsigned DEFAULT NULL,
  `engineer_id` bigint(20) unsigned DEFAULT NULL,
  `unit` varchar(255) DEFAULT NULL,
  `application_id` bigint(20) unsigned DEFAULT NULL,
  `available_budget` decimal(15,2) NOT NULL DEFAULT 0.00,
  `type_of_project` varchar(255) NOT NULL,
  `theme` varchar(255) DEFAULT NULL,
  `subtheme` varchar(255) DEFAULT NULL,
  `activity` varchar(255) DEFAULT NULL,
  `remarks` text DEFAULT NULL,
  `stage` int(11) NOT NULL DEFAULT 1,
  `status` varchar(255) NOT NULL DEFAULT \'Pending\',
  `completion_details` text DEFAULT NULL,
  `community_contributions` text DEFAULT NULL,
  `materials` text DEFAULT NULL,
  `expenses` text DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `total_beneficiary_peoples` int(11) DEFAULT NULL,
  `total_family` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `house_projects_project_id_unique` (`project_id`),
  KEY `house_projects_application_id_idx` (`application_id`),
  KEY `house_projects_project_manager_id_idx` (`project_manager_id`),
  KEY `house_projects_engineer_id_idx` (`engineer_id`),
  KEY `house_projects_donor_id_idx` (`donor_id`),
  KEY `house_projects_status_idx` (`status`),
  KEY `house_projects_stage_idx` (`stage`),
  KEY `house_projects_created_at_idx` (`created_at`),
  CONSTRAINT `house_projects_donor_id_foreign` FOREIGN KEY (`donor_id`) REFERENCES `donors` (`id`) ON DELETE SET NULL,
  CONSTRAINT `house_projects_engineer_id_foreign` FOREIGN KEY (`engineer_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `house_projects_project_manager_id_foreign` FOREIGN KEY (`project_manager_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci');
        DB::statement('CREATE TABLE `shop_other_projects` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `project_id` varchar(255) DEFAULT NULL,
  `project_name` varchar(255) DEFAULT NULL,
  `sponsor` varchar(255) DEFAULT NULL,
  `project_spec` text DEFAULT NULL,
  `agency_project_no` varchar(255) DEFAULT NULL,
  `donor_id` bigint(20) unsigned DEFAULT NULL,
  `project_manager_id` bigint(20) unsigned DEFAULT NULL,
  `engineer_id` bigint(20) unsigned DEFAULT NULL,
  `unit` varchar(255) DEFAULT NULL,
  `application_id` bigint(20) unsigned DEFAULT NULL,
  `available_budget` decimal(15,2) NOT NULL DEFAULT 0.00,
  `type_of_project` varchar(255) NOT NULL,
  `theme` varchar(255) DEFAULT NULL,
  `subtheme` varchar(255) DEFAULT NULL,
  `activity` varchar(255) DEFAULT NULL,
  `remarks` text DEFAULT NULL,
  `stage` int(11) NOT NULL DEFAULT 1,
  `status` varchar(255) NOT NULL DEFAULT \'Pending\',
  `completion_details` text DEFAULT NULL,
  `community_contributions` text DEFAULT NULL,
  `materials` text DEFAULT NULL,
  `expenses` text DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `total_beneficiary_peoples` int(11) DEFAULT NULL,
  `total_family` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `shop_other_projects_project_id_unique` (`project_id`),
  KEY `shop_other_projects_application_id_idx` (`application_id`),
  KEY `shop_other_projects_project_manager_id_idx` (`project_manager_id`),
  KEY `shop_other_projects_engineer_id_idx` (`engineer_id`),
  KEY `shop_other_projects_donor_id_idx` (`donor_id`),
  KEY `shop_other_projects_status_idx` (`status`),
  KEY `shop_other_projects_stage_idx` (`stage`),
  KEY `shop_other_projects_created_at_idx` (`created_at`),
  CONSTRAINT `shop_other_projects_donor_id_foreign` FOREIGN KEY (`donor_id`) REFERENCES `donors` (`id`) ON DELETE SET NULL,
  CONSTRAINT `shop_other_projects_engineer_id_foreign` FOREIGN KEY (`engineer_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `shop_other_projects_project_manager_id_foreign` FOREIGN KEY (`project_manager_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci');
        DB::statement('CREATE TABLE `hospital_clinic_projects` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `project_id` varchar(255) DEFAULT NULL,
  `project_name` varchar(255) DEFAULT NULL,
  `sponsor` varchar(255) DEFAULT NULL,
  `project_spec` text DEFAULT NULL,
  `agency_project_no` varchar(255) DEFAULT NULL,
  `donor_id` bigint(20) unsigned DEFAULT NULL,
  `project_manager_id` bigint(20) unsigned DEFAULT NULL,
  `engineer_id` bigint(20) unsigned DEFAULT NULL,
  `unit` varchar(255) DEFAULT NULL,
  `application_id` bigint(20) unsigned DEFAULT NULL,
  `available_budget` decimal(15,2) NOT NULL DEFAULT 0.00,
  `type_of_project` varchar(255) NOT NULL,
  `theme` varchar(255) DEFAULT NULL,
  `subtheme` varchar(255) DEFAULT NULL,
  `activity` varchar(255) DEFAULT NULL,
  `remarks` text DEFAULT NULL,
  `stage` int(11) NOT NULL DEFAULT 1,
  `status` varchar(255) NOT NULL DEFAULT \'Pending\',
  `completion_details` text DEFAULT NULL,
  `community_contributions` text DEFAULT NULL,
  `materials` text DEFAULT NULL,
  `expenses` text DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `total_beneficiary_peoples` int(11) DEFAULT NULL,
  `total_family` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `hospital_clinic_projects_project_id_unique` (`project_id`),
  KEY `hospital_clinic_projects_application_id_idx` (`application_id`),
  KEY `hospital_clinic_projects_project_manager_id_idx` (`project_manager_id`),
  KEY `hospital_clinic_projects_engineer_id_idx` (`engineer_id`),
  KEY `hospital_clinic_projects_donor_id_idx` (`donor_id`),
  KEY `hospital_clinic_projects_status_idx` (`status`),
  KEY `hospital_clinic_projects_stage_idx` (`stage`),
  KEY `hospital_clinic_projects_created_at_idx` (`created_at`),
  CONSTRAINT `hospital_clinic_projects_donor_id_foreign` FOREIGN KEY (`donor_id`) REFERENCES `donors` (`id`) ON DELETE SET NULL,
  CONSTRAINT `hospital_clinic_projects_engineer_id_foreign` FOREIGN KEY (`engineer_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `hospital_clinic_projects_project_manager_id_foreign` FOREIGN KEY (`project_manager_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci');
        DB::statement('CREATE TABLE `drinking_water_group_projects` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `project_id` varchar(255) DEFAULT NULL,
  `project_name` varchar(255) DEFAULT NULL,
  `sponsor` varchar(255) DEFAULT NULL,
  `project_spec` text DEFAULT NULL,
  `agency_project_no` varchar(255) DEFAULT NULL,
  `donor_id` bigint(20) unsigned DEFAULT NULL,
  `project_manager_id` bigint(20) unsigned DEFAULT NULL,
  `engineer_id` bigint(20) unsigned DEFAULT NULL,
  `unit` varchar(255) DEFAULT NULL,
  `application_id` bigint(20) unsigned DEFAULT NULL,
  `available_budget` decimal(15,2) NOT NULL DEFAULT 0.00,
  `type_of_project` varchar(255) NOT NULL,
  `theme` varchar(255) DEFAULT NULL,
  `subtheme` varchar(255) DEFAULT NULL,
  `activity` varchar(255) DEFAULT NULL,
  `remarks` text DEFAULT NULL,
  `stage` int(11) NOT NULL DEFAULT 1,
  `status` varchar(255) NOT NULL DEFAULT \'Pending\',
  `completion_details` text DEFAULT NULL,
  `community_contributions` text DEFAULT NULL,
  `materials` text DEFAULT NULL,
  `expenses` text DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `total_beneficiary_peoples` int(11) DEFAULT NULL,
  `total_family` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `drinking_water_group_projects_project_id_unique` (`project_id`),
  KEY `drinking_water_group_projects_application_id_idx` (`application_id`),
  KEY `drinking_water_group_projects_project_manager_id_idx` (`project_manager_id`),
  KEY `drinking_water_group_projects_engineer_id_idx` (`engineer_id`),
  KEY `drinking_water_group_projects_donor_id_idx` (`donor_id`),
  KEY `drinking_water_group_projects_status_idx` (`status`),
  KEY `drinking_water_group_projects_stage_idx` (`stage`),
  KEY `drinking_water_group_projects_created_at_idx` (`created_at`),
  CONSTRAINT `drinking_water_group_projects_donor_id_foreign` FOREIGN KEY (`donor_id`) REFERENCES `donors` (`id`) ON DELETE SET NULL,
  CONSTRAINT `drinking_water_group_projects_engineer_id_foreign` FOREIGN KEY (`engineer_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `drinking_water_group_projects_project_manager_id_foreign` FOREIGN KEY (`project_manager_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci');
        DB::statement('CREATE TABLE `drinking_water_individual_projects` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `project_id` varchar(255) DEFAULT NULL,
  `project_name` varchar(255) DEFAULT NULL,
  `sponsor` varchar(255) DEFAULT NULL,
  `project_spec` text DEFAULT NULL,
  `agency_project_no` varchar(255) DEFAULT NULL,
  `donor_id` bigint(20) unsigned DEFAULT NULL,
  `project_manager_id` bigint(20) unsigned DEFAULT NULL,
  `engineer_id` bigint(20) unsigned DEFAULT NULL,
  `unit` varchar(255) DEFAULT NULL,
  `application_id` bigint(20) unsigned DEFAULT NULL,
  `available_budget` decimal(15,2) NOT NULL DEFAULT 0.00,
  `type_of_project` varchar(255) NOT NULL,
  `theme` varchar(255) DEFAULT NULL,
  `subtheme` varchar(255) DEFAULT NULL,
  `activity` varchar(255) DEFAULT NULL,
  `remarks` text DEFAULT NULL,
  `stage` int(11) NOT NULL DEFAULT 1,
  `status` varchar(255) NOT NULL DEFAULT \'Pending\',
  `completion_details` text DEFAULT NULL,
  `community_contributions` text DEFAULT NULL,
  `materials` text DEFAULT NULL,
  `expenses` text DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `total_beneficiary_peoples` int(11) DEFAULT NULL,
  `total_family` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `drinking_water_individual_projects_project_id_unique` (`project_id`),
  KEY `drinking_water_individual_projects_application_id_idx` (`application_id`),
  KEY `drinking_water_individual_projects_project_manager_id_idx` (`project_manager_id`),
  KEY `drinking_water_individual_projects_engineer_id_idx` (`engineer_id`),
  KEY `drinking_water_individual_projects_donor_id_idx` (`donor_id`),
  KEY `drinking_water_individual_projects_status_idx` (`status`),
  KEY `drinking_water_individual_projects_stage_idx` (`stage`),
  KEY `drinking_water_individual_projects_created_at_idx` (`created_at`),
  CONSTRAINT `drinking_water_individual_projects_donor_id_foreign` FOREIGN KEY (`donor_id`) REFERENCES `donors` (`id`) ON DELETE SET NULL,
  CONSTRAINT `drinking_water_individual_projects_engineer_id_foreign` FOREIGN KEY (`engineer_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `drinking_water_individual_projects_project_manager_id_foreign` FOREIGN KEY (`project_manager_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci');
        DB::statement('CREATE TABLE `general_projects` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `project_id` varchar(255) DEFAULT NULL,
  `project_name` varchar(255) DEFAULT NULL,
  `sponsor` varchar(255) DEFAULT NULL,
  `project_spec` text DEFAULT NULL,
  `agency_project_no` varchar(255) DEFAULT NULL,
  `donor_id` bigint(20) unsigned DEFAULT NULL,
  `project_manager_id` bigint(20) unsigned DEFAULT NULL,
  `engineer_id` bigint(20) unsigned DEFAULT NULL,
  `unit` varchar(255) DEFAULT NULL,
  `application_id` bigint(20) unsigned DEFAULT NULL,
  `available_budget` decimal(15,2) NOT NULL DEFAULT 0.00,
  `type_of_project` varchar(255) NOT NULL,
  `theme` varchar(255) DEFAULT NULL,
  `subtheme` varchar(255) DEFAULT NULL,
  `activity` varchar(255) DEFAULT NULL,
  `remarks` text DEFAULT NULL,
  `stage` int(11) NOT NULL DEFAULT 1,
  `status` varchar(255) NOT NULL DEFAULT \'Pending\',
  `completion_details` text DEFAULT NULL,
  `community_contributions` text DEFAULT NULL,
  `materials` text DEFAULT NULL,
  `expenses` text DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `total_beneficiary_peoples` int(11) DEFAULT NULL,
  `total_family` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `general_projects_project_id_unique` (`project_id`),
  KEY `general_projects_application_id_idx` (`application_id`),
  KEY `general_projects_project_manager_id_idx` (`project_manager_id`),
  KEY `general_projects_engineer_id_idx` (`engineer_id`),
  KEY `general_projects_donor_id_idx` (`donor_id`),
  KEY `general_projects_status_idx` (`status`),
  KEY `general_projects_stage_idx` (`stage`),
  KEY `general_projects_created_at_idx` (`created_at`),
  CONSTRAINT `general_projects_donor_id_foreign` FOREIGN KEY (`donor_id`) REFERENCES `donors` (`id`) ON DELETE SET NULL,
  CONSTRAINT `general_projects_engineer_id_foreign` FOREIGN KEY (`engineer_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `general_projects_project_manager_id_foreign` FOREIGN KEY (`project_manager_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci');
        DB::statement('CREATE TABLE `education_center_projects` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `project_id` varchar(255) DEFAULT NULL,
  `project_name` varchar(255) DEFAULT NULL,
  `sponsor` varchar(255) DEFAULT NULL,
  `project_spec` text DEFAULT NULL,
  `agency_project_no` varchar(255) DEFAULT NULL,
  `donor_id` bigint(20) unsigned DEFAULT NULL,
  `project_manager_id` bigint(20) unsigned DEFAULT NULL,
  `engineer_id` bigint(20) unsigned DEFAULT NULL,
  `unit` varchar(255) DEFAULT NULL,
  `application_id` bigint(20) unsigned DEFAULT NULL,
  `available_budget` decimal(15,2) NOT NULL DEFAULT 0.00,
  `type_of_project` varchar(255) NOT NULL,
  `theme` varchar(255) DEFAULT NULL,
  `subtheme` varchar(255) DEFAULT NULL,
  `activity` varchar(255) DEFAULT NULL,
  `remarks` text DEFAULT NULL,
  `stage` int(11) NOT NULL DEFAULT 1,
  `status` varchar(255) NOT NULL DEFAULT \'Pending\',
  `completion_details` text DEFAULT NULL,
  `community_contributions` text DEFAULT NULL,
  `materials` text DEFAULT NULL,
  `expenses` text DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `total_beneficiary_peoples` int(11) DEFAULT NULL,
  `total_family` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `education_center_projects_project_id_unique` (`project_id`),
  KEY `education_center_projects_application_id_idx` (`application_id`),
  KEY `education_center_projects_project_manager_id_idx` (`project_manager_id`),
  KEY `education_center_projects_engineer_id_idx` (`engineer_id`),
  KEY `education_center_projects_donor_id_idx` (`donor_id`),
  KEY `education_center_projects_status_idx` (`status`),
  KEY `education_center_projects_stage_idx` (`stage`),
  KEY `education_center_projects_created_at_idx` (`created_at`),
  CONSTRAINT `education_center_projects_donor_id_foreign` FOREIGN KEY (`donor_id`) REFERENCES `donors` (`id`) ON DELETE SET NULL,
  CONSTRAINT `education_center_projects_engineer_id_foreign` FOREIGN KEY (`engineer_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `education_center_projects_project_manager_id_foreign` FOREIGN KEY (`project_manager_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci');
        DB::statement('CREATE TABLE `cultural_center_projects` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `project_id` varchar(255) DEFAULT NULL,
  `project_name` varchar(255) DEFAULT NULL,
  `sponsor` varchar(255) DEFAULT NULL,
  `project_spec` text DEFAULT NULL,
  `agency_project_no` varchar(255) DEFAULT NULL,
  `donor_id` bigint(20) unsigned DEFAULT NULL,
  `project_manager_id` bigint(20) unsigned DEFAULT NULL,
  `engineer_id` bigint(20) unsigned DEFAULT NULL,
  `unit` varchar(255) DEFAULT NULL,
  `application_id` bigint(20) unsigned DEFAULT NULL,
  `available_budget` decimal(15,2) NOT NULL DEFAULT 0.00,
  `type_of_project` varchar(255) NOT NULL,
  `theme` varchar(255) DEFAULT NULL,
  `subtheme` varchar(255) DEFAULT NULL,
  `activity` varchar(255) DEFAULT NULL,
  `remarks` text DEFAULT NULL,
  `stage` int(11) NOT NULL DEFAULT 1,
  `status` varchar(255) NOT NULL DEFAULT \'Pending\',
  `completion_details` text DEFAULT NULL,
  `community_contributions` text DEFAULT NULL,
  `materials` text DEFAULT NULL,
  `expenses` text DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `total_beneficiary_peoples` int(11) DEFAULT NULL,
  `total_family` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `cultural_center_projects_project_id_unique` (`project_id`),
  KEY `cultural_center_projects_application_id_idx` (`application_id`),
  KEY `cultural_center_projects_project_manager_id_idx` (`project_manager_id`),
  KEY `cultural_center_projects_engineer_id_idx` (`engineer_id`),
  KEY `cultural_center_projects_donor_id_idx` (`donor_id`),
  KEY `cultural_center_projects_status_idx` (`status`),
  KEY `cultural_center_projects_stage_idx` (`stage`),
  KEY `cultural_center_projects_created_at_idx` (`created_at`),
  CONSTRAINT `cultural_center_projects_donor_id_foreign` FOREIGN KEY (`donor_id`) REFERENCES `donors` (`id`) ON DELETE SET NULL,
  CONSTRAINT `cultural_center_projects_engineer_id_foreign` FOREIGN KEY (`engineer_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `cultural_center_projects_project_manager_id_foreign` FOREIGN KEY (`project_manager_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci');
        DB::statement('CREATE TABLE `orphan_care_projects` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `project_id` varchar(255) DEFAULT NULL,
  `project_name` varchar(255) DEFAULT NULL,
  `sponsor` varchar(255) DEFAULT NULL,
  `agency_project_no` varchar(255) DEFAULT NULL,
  `application_id` bigint(20) unsigned DEFAULT NULL,
  `type_of_project` varchar(255) NOT NULL,
  `remarks` text DEFAULT NULL,
  `stage` int(11) NOT NULL DEFAULT 1,
  `status` varchar(255) NOT NULL DEFAULT \'Pending\',
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `location` varchar(255) DEFAULT NULL,
  `total_beneficiary_peoples` int(11) DEFAULT NULL,
  `total_family` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `orphan_care_projects_project_id_unique` (`project_id`),
  KEY `orphan_care_projects_application_id_idx` (`application_id`),
  KEY `orphan_care_projects_status_idx` (`status`),
  KEY `orphan_care_projects_stage_idx` (`stage`),
  KEY `orphan_care_projects_created_at_idx` (`created_at`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci');
        DB::statement('CREATE TABLE `orphan_care_funds` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `agency_project_no` varchar(255) DEFAULT NULL,
  `date` varchar(255) NOT NULL,
  `amount` decimal(15,2) NOT NULL,
  `account_name` varchar(255) DEFAULT NULL,
  `account_number` varchar(255) DEFAULT NULL,
  `ifsc_number` varchar(255) DEFAULT NULL,
  `donor` varchar(255) NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `orphan_care_funds_donor_foreign` (`donor`),
  CONSTRAINT `orphan_care_funds_donor_foreign` FOREIGN KEY (`donor`) REFERENCES `donors` (`name`) ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci');
        DB::statement('CREATE TABLE `orphan_care_programmes` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `orphan_care_project_id` bigint(20) unsigned NOT NULL,
  `programme_name` varchar(255) NOT NULL,
  `date` varchar(255) DEFAULT NULL,
  `place` varchar(255) DEFAULT NULL,
  `remarks` text DEFAULT NULL,
  `present_ticked` tinyint(1) NOT NULL DEFAULT 0,
  `photo_ticked` tinyint(1) NOT NULL DEFAULT 0,
  `marklist_ticked` tinyint(1) NOT NULL DEFAULT 0,
  `thanks_letter_ticked` tinyint(1) NOT NULL DEFAULT 0,
  `report_form_ticked` tinyint(1) NOT NULL DEFAULT 0,
  `medical_certificate_ticked` tinyint(1) NOT NULL DEFAULT 0,
  `other_document_ticked` tinyint(1) NOT NULL DEFAULT 0,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `orphan_care_programmes_orphan_care_project_id_foreign` (`orphan_care_project_id`),
  CONSTRAINT `orphan_care_programmes_orphan_care_project_id_foreign` FOREIGN KEY (`orphan_care_project_id`) REFERENCES `orphan_care_projects` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci');
        DB::statement('CREATE TABLE `differently_abled_projects` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `project_id` varchar(255) DEFAULT NULL,
  `project_name` varchar(255) DEFAULT NULL,
  `sponsor` varchar(255) DEFAULT NULL,
  `agency_project_no` varchar(255) DEFAULT NULL,
  `application_id` bigint(20) unsigned DEFAULT NULL,
  `type_of_project` varchar(255) NOT NULL,
  `remarks` text DEFAULT NULL,
  `stage` int(11) NOT NULL DEFAULT 1,
  `status` varchar(255) NOT NULL DEFAULT \'Pending\',
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `location` varchar(255) DEFAULT NULL,
  `total_beneficiary_peoples` int(11) DEFAULT NULL,
  `total_family` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `differently_abled_projects_project_id_unique` (`project_id`),
  KEY `differently_abled_projects_application_id_idx` (`application_id`),
  KEY `differently_abled_projects_status_idx` (`status`),
  KEY `differently_abled_projects_stage_idx` (`stage`),
  KEY `differently_abled_projects_created_at_idx` (`created_at`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci');
        DB::statement('CREATE TABLE `differently_abled_funds` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `agency_project_no` varchar(255) DEFAULT NULL,
  `date` varchar(255) NOT NULL,
  `amount` decimal(15,2) NOT NULL,
  `account_name` varchar(255) DEFAULT NULL,
  `account_number` varchar(255) DEFAULT NULL,
  `ifsc_number` varchar(255) DEFAULT NULL,
  `donor` varchar(255) NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `differently_abled_funds_donor_foreign` (`donor`),
  CONSTRAINT `differently_abled_funds_donor_foreign` FOREIGN KEY (`donor`) REFERENCES `donors` (`name`) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci');
        DB::statement('CREATE TABLE `differently_abled_programmes` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `differently_abled_project_id` bigint(20) unsigned NOT NULL,
  `programme_name` varchar(255) NOT NULL,
  `date` varchar(255) DEFAULT NULL,
  `place` varchar(255) DEFAULT NULL,
  `remarks` text DEFAULT NULL,
  `present_ticked` tinyint(1) NOT NULL DEFAULT 0,
  `photo_ticked` tinyint(1) NOT NULL DEFAULT 0,
  `marklist_ticked` tinyint(1) NOT NULL DEFAULT 0,
  `thanks_letter_ticked` tinyint(1) NOT NULL DEFAULT 0,
  `report_form_ticked` tinyint(1) NOT NULL DEFAULT 0,
  `medical_certificate_ticked` tinyint(1) NOT NULL DEFAULT 0,
  `other_document_ticked` tinyint(1) NOT NULL DEFAULT 0,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_da_prog_proj_id` (`differently_abled_project_id`),
  CONSTRAINT `fk_da_prog_proj_id` FOREIGN KEY (`differently_abled_project_id`) REFERENCES `differently_abled_projects` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci');
        DB::statement('CREATE TABLE `family_aid_projects` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `project_id` varchar(255) DEFAULT NULL,
  `project_name` varchar(255) DEFAULT NULL,
  `sponsor` varchar(255) DEFAULT NULL,
  `agency_project_no` varchar(255) DEFAULT NULL,
  `application_id` bigint(20) unsigned DEFAULT NULL,
  `type_of_project` varchar(255) NOT NULL,
  `remarks` text DEFAULT NULL,
  `stage` int(11) NOT NULL DEFAULT 1,
  `status` varchar(255) NOT NULL DEFAULT \'Pending\',
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `location` varchar(255) DEFAULT NULL,
  `total_beneficiary_peoples` int(11) DEFAULT NULL,
  `total_family` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `family_aid_projects_project_id_unique` (`project_id`),
  KEY `family_aid_projects_application_id_idx` (`application_id`),
  KEY `family_aid_projects_status_idx` (`status`),
  KEY `family_aid_projects_stage_idx` (`stage`),
  KEY `family_aid_projects_created_at_idx` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci');
        DB::statement('CREATE TABLE `family_aid_funds` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `agency_project_no` varchar(255) DEFAULT NULL,
  `date` varchar(255) NOT NULL,
  `amount` decimal(15,2) NOT NULL,
  `account_name` varchar(255) DEFAULT NULL,
  `account_number` varchar(255) DEFAULT NULL,
  `ifsc_number` varchar(255) DEFAULT NULL,
  `donor` varchar(255) NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `family_aid_funds_donor_foreign` (`donor`),
  CONSTRAINT `family_aid_funds_donor_foreign` FOREIGN KEY (`donor`) REFERENCES `donors` (`name`) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci');
        DB::statement('CREATE TABLE `family_aid_programmes` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `family_aid_project_id` bigint(20) unsigned NOT NULL,
  `programme_name` varchar(255) NOT NULL,
  `date` varchar(255) DEFAULT NULL,
  `place` varchar(255) DEFAULT NULL,
  `remarks` text DEFAULT NULL,
  `present_ticked` tinyint(1) NOT NULL DEFAULT 0,
  `photo_ticked` tinyint(1) NOT NULL DEFAULT 0,
  `marklist_ticked` tinyint(1) NOT NULL DEFAULT 0,
  `thanks_letter_ticked` tinyint(1) NOT NULL DEFAULT 0,
  `report_form_ticked` tinyint(1) NOT NULL DEFAULT 0,
  `medical_certificate_ticked` tinyint(1) NOT NULL DEFAULT 0,
  `other_document_ticked` tinyint(1) NOT NULL DEFAULT 0,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_fa_prog_proj_id` (`family_aid_project_id`),
  CONSTRAINT `fk_fa_prog_proj_id` FOREIGN KEY (`family_aid_project_id`) REFERENCES `family_aid_projects` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci');
        DB::statement('CREATE TABLE `contractors` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `phone` varchar(255) DEFAULT NULL,
  `company_name` varchar(255) DEFAULT NULL,
  `address` text DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci');
        DB::statement('CREATE TABLE `project_contractors` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `project_id` bigint(20) unsigned NOT NULL,
  `project_type` varchar(255) NOT NULL,
  `contractor_id` bigint(20) unsigned DEFAULT NULL,
  `contractor_name` varchar(255) NOT NULL,
  `phone` varchar(255) DEFAULT NULL,
  `company_name` varchar(255) DEFAULT NULL,
  `address` text DEFAULT NULL,
  `type_of_contract` varchar(255) DEFAULT NULL,
  `purpose_of_contract` varchar(255) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `project_contractors_project_id_project_type_index` (`project_id`,`project_type`),
  KEY `project_contractors_contractor_id_foreign` (`contractor_id`),
  CONSTRAINT `project_contractors_contractor_id_foreign` FOREIGN KEY (`contractor_id`) REFERENCES `contractors` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=17 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci');
        DB::statement('CREATE TABLE `project_community_contributions` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `project_id` bigint(20) unsigned NOT NULL,
  `project_type` varchar(255) NOT NULL,
  `item` varchar(255) NOT NULL,
  `amount` decimal(15,2) NOT NULL DEFAULT 0.00,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `project_contrib_index` (`project_id`,`project_type`)
) ENGINE=InnoDB AUTO_INCREMENT=18 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci');
        DB::statement('CREATE TABLE `project_completion_details` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `project_id` bigint(20) unsigned NOT NULL,
  `project_type` varchar(255) NOT NULL,
  `total_project_cost` decimal(15,2) DEFAULT NULL,
  `total_amount` decimal(15,2) DEFAULT NULL,
  `amount_paid_by_donor` decimal(15,2) DEFAULT NULL,
  `community_contribution` decimal(15,2) DEFAULT NULL,
  `any_other` decimal(15,2) DEFAULT NULL,
  `deductions` decimal(15,2) DEFAULT NULL,
  `handover_date` date DEFAULT NULL,
  `handover_remarks` text DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `project_completion_unique` (`project_id`,`project_type`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci');
        DB::statement('CREATE TABLE `project_documents` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `project_id` bigint(20) unsigned NOT NULL,
  `project_type` varchar(255) NOT NULL,
  `land_document` varchar(255) NOT NULL DEFAULT \'0\',
  `land_document_ticked_at` timestamp NULL DEFAULT NULL,
  `possession_certificate` varchar(255) NOT NULL DEFAULT \'0\',
  `possession_certificate_ticked_at` timestamp NULL DEFAULT NULL,
  `tax_receipt` varchar(255) NOT NULL DEFAULT \'0\',
  `tax_receipt_ticked_at` timestamp NULL DEFAULT NULL,
  `recommendation_letter` varchar(255) NOT NULL DEFAULT \'0\',
  `recommendation_letter_ticked_at` timestamp NULL DEFAULT NULL,
  `committee_minutes` varchar(255) NOT NULL DEFAULT \'0\',
  `committee_minutes_ticked_at` timestamp NULL DEFAULT NULL,
  `permit_copy` varchar(255) NOT NULL DEFAULT \'0\',
  `permit_copy_ticked_at` timestamp NULL DEFAULT NULL,
  `plan` varchar(255) NOT NULL DEFAULT \'0\',
  `plan_ticked_at` timestamp NULL DEFAULT NULL,
  `tender_schedule_sheet` varchar(255) NOT NULL DEFAULT \'0\',
  `tender_schedule_sheet_ticked_at` timestamp NULL DEFAULT NULL,
  `site_study` varchar(255) NOT NULL DEFAULT \'0\',
  `site_study_ticked_at` timestamp NULL DEFAULT NULL,
  `quotations` varchar(255) NOT NULL DEFAULT \'0\',
  `quotations_ticked_at` timestamp NULL DEFAULT NULL,
  `quotations_approval_form` varchar(255) NOT NULL DEFAULT \'0\',
  `quotations_approval_form_ticked_at` timestamp NULL DEFAULT NULL,
  `work_order_letter` varchar(255) NOT NULL DEFAULT \'0\',
  `work_order_letter_ticked_at` timestamp NULL DEFAULT NULL,
  `meeting_minutes_copy` varchar(255) NOT NULL DEFAULT \'0\',
  `meeting_minutes_copy_ticked_at` timestamp NULL DEFAULT NULL,
  `agreement_with_contractor` varchar(255) NOT NULL DEFAULT \'0\',
  `agreement_with_contractor_ticked_at` timestamp NULL DEFAULT NULL,
  `agreement_with_committee` varchar(255) NOT NULL DEFAULT \'0\',
  `agreement_with_committee_ticked_at` timestamp NULL DEFAULT NULL,
  `project_summary_form` varchar(255) NOT NULL DEFAULT \'0\',
  `project_summary_form_ticked_at` timestamp NULL DEFAULT NULL,
  `completion_certificate` varchar(255) NOT NULL DEFAULT \'0\',
  `completion_certificate_ticked_at` timestamp NULL DEFAULT NULL,
  `measurement_book` varchar(255) NOT NULL DEFAULT \'0\',
  `measurement_book_ticked_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `location_map_link` text DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `project_documents_project_id_project_type_index` (`project_id`,`project_type`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci');
        DB::statement('CREATE TABLE `project_expenses` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `project_id` bigint(20) unsigned NOT NULL,
  `project_type` varchar(255) NOT NULL,
  `material_index` int(11) DEFAULT NULL,
  `comm_index` int(11) DEFAULT NULL,
  `expense_name` varchar(255) NOT NULL,
  `quantity` int(11) NOT NULL DEFAULT 1,
  `amount` decimal(15,2) NOT NULL DEFAULT 0.00,
  `type` varchar(255) NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `project_expenses_project_id_project_type_index` (`project_id`,`project_type`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci');
        DB::statement('CREATE TABLE `project_inspections` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `project_id` bigint(20) unsigned NOT NULL,
  `project_type` varchar(255) NOT NULL,
  `name` varchar(255) NOT NULL,
  `designation` varchar(255) NOT NULL,
  `date` date NOT NULL,
  `remarks` text DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `project_inspections_project_id_project_type_index` (`project_id`,`project_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci');
        DB::statement('CREATE TABLE `project_photos` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `project_id` bigint(20) unsigned NOT NULL,
  `project_type` varchar(255) NOT NULL,
  `photos` text DEFAULT NULL,
  `photos_before` text DEFAULT NULL,
  `photos_starting` text DEFAULT NULL,
  `photos_inbetween` text DEFAULT NULL,
  `photos_after` text DEFAULT NULL,
  `photos_banner` text DEFAULT NULL,
  `photos_stone` text DEFAULT NULL,
  `photos_inauguration` text DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `project_files_project_id_project_type_unique` (`project_id`,`project_type`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci');
        DB::statement('CREATE TABLE `project_site_studies` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `project_id` bigint(20) unsigned NOT NULL,
  `project_type` varchar(255) NOT NULL,
  `report` longtext DEFAULT NULL,
  `remarks` text DEFAULT NULL,
  `file_path` varchar(255) DEFAULT NULL,
  `status` varchar(255) NOT NULL DEFAULT \'pending\',
  `ticked_at` timestamp NULL DEFAULT NULL,
  `created_by` bigint(20) unsigned DEFAULT NULL,
  `updated_by` bigint(20) unsigned DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `project_site_studies_project_id_project_type_index` (`project_id`,`project_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci');
        DB::statement('CREATE TABLE `project_statuses` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `project_id` bigint(20) unsigned NOT NULL,
  `project_type` varchar(255) NOT NULL,
  `status` varchar(255) DEFAULT NULL,
  `status_custom` varchar(255) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `coo_approved_at` timestamp NULL DEFAULT NULL,
  `coo_approver_id` bigint(20) unsigned DEFAULT NULL,
  `coo_remarks` text DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `project_statuses_project_id_project_type_index` (`project_id`,`project_type`),
  KEY `project_statuses_coo_approver_id_foreign` (`coo_approver_id`),
  CONSTRAINT `project_statuses_coo_approver_id_foreign` FOREIGN KEY (`coo_approver_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci');
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('project_statuses');
        Schema::dropIfExists('project_site_studies');
        Schema::dropIfExists('project_photos');
        Schema::dropIfExists('project_inspections');
        Schema::dropIfExists('project_expenses');
        Schema::dropIfExists('project_documents');
        Schema::dropIfExists('project_completion_details');
        Schema::dropIfExists('project_community_contributions');
        Schema::dropIfExists('project_contractors');
        Schema::dropIfExists('contractors');
        Schema::dropIfExists('family_aid_programmes');
        Schema::dropIfExists('family_aid_funds');
        Schema::dropIfExists('family_aid_projects');
        Schema::dropIfExists('differently_abled_programmes');
        Schema::dropIfExists('differently_abled_funds');
        Schema::dropIfExists('differently_abled_projects');
        Schema::dropIfExists('orphan_care_programmes');
        Schema::dropIfExists('orphan_care_funds');
        Schema::dropIfExists('orphan_care_projects');
        Schema::dropIfExists('cultural_center_projects');
        Schema::dropIfExists('education_center_projects');
        Schema::dropIfExists('general_projects');
        Schema::dropIfExists('drinking_water_individual_projects');
        Schema::dropIfExists('drinking_water_group_projects');
        Schema::dropIfExists('hospital_clinic_projects');
        Schema::dropIfExists('shop_other_projects');
        Schema::dropIfExists('house_projects');
    }
};
