<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        DB::statement('CREATE TABLE `applications` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `applicant_name` varchar(255) NOT NULL,
  `amount_requested` int(11) DEFAULT NULL,
  `status` varchar(255) NOT NULL DEFAULT \'Pending\',
  `rejected_reason` text DEFAULT NULL,
  `contact_email` varchar(255) DEFAULT NULL,
  `details` text DEFAULT NULL,
  `meta` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`meta`)),
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci');
        DB::statement('CREATE TABLE `orphan_care_applications` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `applicant_name` varchar(255) NOT NULL,
  `guardian_name` varchar(255) DEFAULT NULL,
  `contact_email` varchar(255) DEFAULT NULL,
  `contact_number_1` text DEFAULT NULL,
  `contact_number_2` text DEFAULT NULL,
  `house_name` text DEFAULT NULL,
  `place` text DEFAULT NULL,
  `post_office` text DEFAULT NULL,
  `village` text DEFAULT NULL,
  `panchayat` text DEFAULT NULL,
  `district` text DEFAULT NULL,
  `state` text DEFAULT NULL,
  `pin_code` text DEFAULT NULL,
  `gender` varchar(255) DEFAULT NULL,
  `amount_requested` varchar(255) DEFAULT NULL,
  `additional_note` text DEFAULT NULL,
  `recommendation_name` varchar(255) DEFAULT NULL,
  `recommendation_organization` varchar(255) DEFAULT NULL,
  `recommendation_organization_other` varchar(255) DEFAULT NULL,
  `recommendation_phone` varchar(255) DEFAULT NULL,
  `recommendation_position` varchar(255) DEFAULT NULL,
  `status` varchar(255) NOT NULL DEFAULT \'Pending\',
  `rejected_reason` text DEFAULT NULL,
  `agency_number` varchar(255) DEFAULT NULL,
  `agency_name` varchar(255) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `father_name` varchar(255) DEFAULT NULL,
  `grandfather_name` varchar(255) DEFAULT NULL,
  `student_photo` varchar(255) DEFAULT NULL,
  `mother_name` varchar(255) DEFAULT NULL,
  `mothers_father_name` varchar(255) DEFAULT NULL,
  `dob` varchar(255) DEFAULT NULL,
  `age` varchar(255) DEFAULT NULL,
  `aadhar_number` varchar(255) DEFAULT NULL,
  `guardian_relation` varchar(255) DEFAULT NULL,
  `father_death_date` varchar(255) DEFAULT NULL,
  `father_death_cause` varchar(255) DEFAULT NULL,
  `mother_alive_status` varchar(255) DEFAULT NULL,
  `mother_remarried_status` varchar(255) DEFAULT NULL,
  `mother_death_date` varchar(255) DEFAULT NULL,
  `mother_death_cause` varchar(255) DEFAULT NULL,
  `siblings_male` varchar(255) DEFAULT NULL,
  `siblings_female` varchar(255) DEFAULT NULL,
  `siblings_total` varchar(255) DEFAULT NULL,
  `monthly_income` varchar(255) DEFAULT NULL,
  `monthly_expense` varchar(255) DEFAULT NULL,
  `sponsorship_details` varchar(255) DEFAULT NULL,
  `house_type` varchar(255) DEFAULT NULL,
  `school_name` varchar(255) DEFAULT NULL,
  `school_class` varchar(255) DEFAULT NULL,
  `madrassa_name` varchar(255) DEFAULT NULL,
  `madrassa_class` varchar(255) DEFAULT NULL,
  `not_studying_reason` varchar(255) DEFAULT NULL,
  `health_status` varchar(255) DEFAULT NULL,
  `sponsor_status` varchar(255) NOT NULL DEFAULT \'Not Sponsored\',
  `town` varchar(255) DEFAULT NULL,
  `locality_pin_code` varchar(255) DEFAULT NULL,
  `locality_place` varchar(255) DEFAULT NULL,
  `locality_village` varchar(255) DEFAULT NULL,
  `locality_post` varchar(255) DEFAULT NULL,
  `locality_panchayath` varchar(255) DEFAULT NULL,
  `locality_district` varchar(255) DEFAULT NULL,
  `locality_state` varchar(255) DEFAULT NULL,
  `submitted_before` varchar(255) DEFAULT NULL,
  `received_support_before` varchar(255) DEFAULT NULL,
  `financial_support_purpose` varchar(255) DEFAULT NULL,
  `permitted_type` varchar(255) DEFAULT NULL,
  `cluster_id` bigint(20) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `orphan_care_applications_status_idx` (`status`),
  KEY `orphan_care_applications_created_at_idx` (`created_at`)
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci');
        DB::statement('CREATE TABLE `differently_abled_applications` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `applicant_name` varchar(255) NOT NULL,
  `guardian_name` varchar(255) DEFAULT NULL,
  `contact_email` varchar(255) DEFAULT NULL,
  `contact_number_1` text DEFAULT NULL,
  `contact_number_2` text DEFAULT NULL,
  `house_name` text DEFAULT NULL,
  `place` text DEFAULT NULL,
  `post_office` text DEFAULT NULL,
  `panchayat` text DEFAULT NULL,
  `district` text DEFAULT NULL,
  `state` text DEFAULT NULL,
  `pin_code` text DEFAULT NULL,
  `disability_type` varchar(255) DEFAULT NULL,
  `disability_percentage` int(11) DEFAULT NULL,
  `monthly_income` varchar(255) DEFAULT NULL,
  `amount_requested` varchar(255) DEFAULT NULL,
  `additional_note` text DEFAULT NULL,
  `recommendation_name` varchar(255) DEFAULT NULL,
  `recommendation_organization` varchar(255) DEFAULT NULL,
  `recommendation_organization_other` varchar(255) DEFAULT NULL,
  `recommendation_phone` varchar(255) DEFAULT NULL,
  `recommendation_position` varchar(255) DEFAULT NULL,
  `status` varchar(255) NOT NULL DEFAULT \'Pending\',
  `rejected_reason` text DEFAULT NULL,
  `agency_number` varchar(255) DEFAULT NULL,
  `agency_name` varchar(255) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `father_name` varchar(255) DEFAULT NULL,
  `fathers_father` varchar(255) DEFAULT NULL,
  `mother_name` varchar(255) DEFAULT NULL,
  `gender` varchar(255) DEFAULT NULL,
  `aadhar_number` varchar(255) DEFAULT NULL,
  `dob` varchar(255) DEFAULT NULL,
  `age` varchar(255) DEFAULT NULL,
  `marital_status` varchar(255) DEFAULT NULL,
  `guardian_relation` varchar(255) DEFAULT NULL,
  `male_members` int(11) DEFAULT NULL,
  `female_members` int(11) DEFAULT NULL,
  `total_members` int(11) DEFAULT NULL,
  `people_with_disabilities` int(11) DEFAULT NULL,
  `monthly_cost` int(11) DEFAULT NULL,
  `income_source` varchar(255) DEFAULT NULL,
  `studying_institution` varchar(255) DEFAULT NULL,
  `not_studying_reason` varchar(255) DEFAULT NULL,
  `health_status` varchar(255) DEFAULT NULL,
  `disability_date` varchar(255) DEFAULT NULL,
  `disability_level` varchar(255) DEFAULT NULL,
  `other_help` varchar(255) DEFAULT NULL,
  `description` varchar(255) DEFAULT NULL,
  `accommodation` varchar(255) DEFAULT NULL,
  `sponsor_status` varchar(255) NOT NULL DEFAULT \'Not Sponsored\',
  `student_photo` varchar(255) DEFAULT NULL,
  `locality_pin_code` varchar(255) DEFAULT NULL,
  `locality_place` varchar(255) DEFAULT NULL,
  `locality_village` varchar(255) DEFAULT NULL,
  `locality_post` varchar(255) DEFAULT NULL,
  `locality_panchayath` varchar(255) DEFAULT NULL,
  `locality_district` varchar(255) DEFAULT NULL,
  `locality_state` varchar(255) DEFAULT NULL,
  `submitted_before` varchar(255) DEFAULT NULL,
  `received_support_before` varchar(255) DEFAULT NULL,
  `financial_support_purpose` varchar(255) DEFAULT NULL,
  `permitted_type` varchar(255) DEFAULT NULL,
  `village` text DEFAULT NULL,
  `cluster_id` bigint(20) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `differently_abled_applications_status_idx` (`status`),
  KEY `differently_abled_applications_created_at_idx` (`created_at`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci');
        DB::statement('CREATE TABLE `family_aid_applications` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `applicant_name` varchar(255) NOT NULL,
  `contact_email` varchar(255) DEFAULT NULL,
  `contact_number_1` text DEFAULT NULL,
  `contact_number_2` text DEFAULT NULL,
  `house_name` text DEFAULT NULL,
  `place` text DEFAULT NULL,
  `post_office` text DEFAULT NULL,
  `panchayat` text DEFAULT NULL,
  `district` text DEFAULT NULL,
  `state` text DEFAULT NULL,
  `pin_code` text DEFAULT NULL,
  `monthly_income` varchar(255) DEFAULT NULL,
  `occupation` varchar(255) DEFAULT NULL,
  `amount_requested` varchar(255) DEFAULT NULL,
  `additional_note` text DEFAULT NULL,
  `recommendation_name` varchar(255) DEFAULT NULL,
  `recommendation_organization` varchar(255) DEFAULT NULL,
  `recommendation_organization_other` varchar(255) DEFAULT NULL,
  `recommendation_phone` varchar(255) DEFAULT NULL,
  `recommendation_position` varchar(255) DEFAULT NULL,
  `status` varchar(255) NOT NULL DEFAULT \'Pending\',
  `rejected_reason` text DEFAULT NULL,
  `agency_number` varchar(255) DEFAULT NULL,
  `agency_name` varchar(255) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `father_name` varchar(255) DEFAULT NULL,
  `mother_name` varchar(255) DEFAULT NULL,
  `fathers_father` varchar(255) DEFAULT NULL,
  `dob` varchar(255) DEFAULT NULL,
  `age` varchar(255) DEFAULT NULL,
  `aadhar_number` varchar(255) DEFAULT NULL,
  `children_total` varchar(255) DEFAULT NULL,
  `children_male` varchar(255) DEFAULT NULL,
  `children_female` varchar(255) DEFAULT NULL,
  `nri_status` varchar(255) DEFAULT NULL,
  `other_income_sources` varchar(255) DEFAULT NULL,
  `health_status` varchar(255) DEFAULT NULL,
  `disability_status` varchar(255) DEFAULT NULL,
  `routine_treatment_explanation` text DEFAULT NULL,
  `chronic_patients_description` text DEFAULT NULL,
  `residence_info` varchar(255) DEFAULT NULL,
  `own_house_condition` varchar(255) DEFAULT NULL,
  `own_place_status` varchar(255) DEFAULT NULL,
  `own_place_size` varchar(255) DEFAULT NULL,
  `sequel_status` varchar(255) DEFAULT NULL,
  `welfare_assistance_areas` text DEFAULT NULL,
  `sponsor_status` varchar(255) NOT NULL DEFAULT \'Not Sponsored\',
  `student_photo` varchar(255) DEFAULT NULL,
  `gender` varchar(255) DEFAULT NULL,
  `locality_pin_code` varchar(255) DEFAULT NULL,
  `locality_place` varchar(255) DEFAULT NULL,
  `locality_village` varchar(255) DEFAULT NULL,
  `locality_post` varchar(255) DEFAULT NULL,
  `locality_panchayath` varchar(255) DEFAULT NULL,
  `locality_district` varchar(255) DEFAULT NULL,
  `locality_state` varchar(255) DEFAULT NULL,
  `submitted_before` varchar(255) DEFAULT NULL,
  `received_support_before` varchar(255) DEFAULT NULL,
  `financial_support_purpose` varchar(255) DEFAULT NULL,
  `permitted_type` varchar(255) DEFAULT NULL,
  `village` text DEFAULT NULL,
  `cluster_id` bigint(20) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `family_aid_applications_status_idx` (`status`),
  KEY `family_aid_applications_created_at_idx` (`created_at`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci');
        DB::statement('CREATE TABLE `house_applications` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `applicant_name` varchar(255) NOT NULL,
  `contact_email` varchar(255) DEFAULT NULL,
  `contact_number_1` text DEFAULT NULL,
  `contact_number_2` text DEFAULT NULL,
  `house_name` text DEFAULT NULL,
  `place` text DEFAULT NULL,
  `post_office` text DEFAULT NULL,
  `village` text DEFAULT NULL,
  `panchayat` text DEFAULT NULL,
  `district` text DEFAULT NULL,
  `state` text DEFAULT NULL,
  `pin_code` text DEFAULT NULL,
  `submitted_before` varchar(255) DEFAULT NULL,
  `received_support_before` varchar(255) DEFAULT NULL,
  `financial_support_purpose` varchar(255) DEFAULT NULL,
  `locality_place` varchar(255) DEFAULT NULL,
  `locality_post` varchar(255) DEFAULT NULL,
  `locality_village` varchar(255) DEFAULT NULL,
  `locality_panchayath` varchar(255) DEFAULT NULL,
  `locality_district` varchar(255) DEFAULT NULL,
  `locality_state` varchar(255) DEFAULT NULL,
  `locality_pin_code` varchar(255) DEFAULT NULL,
  `monthly_income` varchar(255) DEFAULT NULL,
  `occupation` varchar(255) DEFAULT NULL,
  `building_area_sq` varchar(255) DEFAULT NULL,
  `amount_requested` varchar(255) DEFAULT NULL,
  `legal_approvals_status` varchar(255) DEFAULT NULL,
  `permitted_type` varchar(255) DEFAULT NULL,
  `additional_note` text DEFAULT NULL,
  `recommendation_name` varchar(255) DEFAULT NULL,
  `recommendation_organization` varchar(255) DEFAULT NULL,
  `recommendation_organization_other` varchar(255) DEFAULT NULL,
  `recommendation_phone` varchar(255) DEFAULT NULL,
  `recommendation_position` varchar(255) DEFAULT NULL,
  `status` varchar(255) NOT NULL DEFAULT \'Pending\',
  `rejected_reason` text DEFAULT NULL,
  `agency_number` varchar(255) DEFAULT NULL,
  `agency_name` varchar(255) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `age` varchar(255) DEFAULT NULL,
  `father_name` varchar(255) DEFAULT NULL,
  `mother_name` varchar(255) DEFAULT NULL,
  `gender` varchar(255) DEFAULT NULL,
  `married` varchar(255) DEFAULT NULL,
  `num_children` varchar(255) DEFAULT NULL,
  `num_male_children` varchar(255) DEFAULT NULL,
  `num_female_children` varchar(255) DEFAULT NULL,
  `has_occupation` varchar(255) DEFAULT NULL,
  `other_income` varchar(255) DEFAULT NULL,
  `health_status` varchar(255) DEFAULT NULL,
  `daily_treatment_explanation` text DEFAULT NULL,
  `accommodation_details` text DEFAULT NULL,
  `own_place` varchar(255) DEFAULT NULL,
  `own_place_details` varchar(255) DEFAULT NULL,
  `land_type` varchar(255) DEFAULT NULL,
  `desired_model` varchar(255) DEFAULT NULL,
  `intended_house_form` varchar(255) DEFAULT NULL,
  `office_build_house` varchar(255) DEFAULT NULL,
  `children_total` varchar(255) DEFAULT NULL,
  `children_male` varchar(255) DEFAULT NULL,
  `children_female` varchar(255) DEFAULT NULL,
  `house_type` varchar(255) DEFAULT NULL,
  `permission` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `house_applications_status_idx` (`status`),
  KEY `house_applications_created_at_idx` (`created_at`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci');
        DB::statement('CREATE TABLE `shop_other_applications` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `applicant_name` varchar(255) DEFAULT NULL,
  `committee_name` varchar(255) DEFAULT NULL,
  `reg_number` varchar(255) DEFAULT NULL,
  `year` varchar(255) DEFAULT NULL,
  `pin_code` varchar(255) DEFAULT NULL,
  `place` varchar(255) DEFAULT NULL,
  `village` varchar(255) DEFAULT NULL,
  `post_office` varchar(255) DEFAULT NULL,
  `panchayat` varchar(255) DEFAULT NULL,
  `district` varchar(255) DEFAULT NULL,
  `state` varchar(255) DEFAULT NULL,
  `contact_number_1` varchar(255) DEFAULT NULL,
  `contact_number_2` varchar(255) DEFAULT NULL,
  `mahallu_name` varchar(255) DEFAULT NULL,
  `locality_pin_code` varchar(255) DEFAULT NULL,
  `locality_place` varchar(255) DEFAULT NULL,
  `locality_village` varchar(255) DEFAULT NULL,
  `locality_post` varchar(255) DEFAULT NULL,
  `locality_panchayath` varchar(255) DEFAULT NULL,
  `locality_district` varchar(255) DEFAULT NULL,
  `locality_state` varchar(255) DEFAULT NULL,
  `families_in_mahallu` varchar(255) DEFAULT NULL,
  `site_has_building` varchar(255) DEFAULT NULL,
  `status_of_current_building` varchar(255) DEFAULT NULL,
  `status_of_current_building_other` varchar(255) DEFAULT NULL,
  `num_rooms` varchar(255) DEFAULT NULL,
  `office_shop` varchar(255) DEFAULT NULL,
  `building_area_sq` varchar(255) DEFAULT NULL,
  `amount_requested` varchar(255) DEFAULT NULL,
  `legal_approvals_status` varchar(255) DEFAULT NULL,
  `permitted_type` varchar(255) DEFAULT NULL,
  `area` varchar(255) DEFAULT NULL,
  `project_area` varchar(255) DEFAULT NULL,
  `additional_note` text DEFAULT NULL,
  `recommendation_name` varchar(255) DEFAULT NULL,
  `recommendation_organization` varchar(255) DEFAULT NULL,
  `recommendation_organization_other` varchar(255) DEFAULT NULL,
  `recommendation_phone` varchar(255) DEFAULT NULL,
  `recommendation_position` varchar(255) DEFAULT NULL,
  `contact_email` varchar(255) DEFAULT NULL,
  `status` varchar(255) NOT NULL DEFAULT \'Pending\',
  `rejected_reason` text DEFAULT NULL,
  `agency_number` varchar(255) DEFAULT NULL,
  `agency_name` varchar(255) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `house_name` text DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `shop_other_applications_status_idx` (`status`),
  KEY `shop_other_applications_created_at_idx` (`created_at`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci');
        DB::statement('CREATE TABLE `hospital_clinic_applications` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `applicant_name` varchar(255) NOT NULL,
  `committee_name` varchar(255) DEFAULT NULL,
  `reg_number` varchar(255) DEFAULT NULL,
  `year` varchar(255) DEFAULT NULL,
  `contact_email` varchar(255) DEFAULT NULL,
  `contact_number_1` text DEFAULT NULL,
  `contact_number_2` text DEFAULT NULL,
  `place` text DEFAULT NULL,
  `post_office` text DEFAULT NULL,
  `village` text DEFAULT NULL,
  `panchayat` text DEFAULT NULL,
  `district` text DEFAULT NULL,
  `state` text DEFAULT NULL,
  `pin_code` text DEFAULT NULL,
  `mahallu_name` varchar(255) DEFAULT NULL,
  `locality_place` varchar(255) DEFAULT NULL,
  `locality_post` varchar(255) DEFAULT NULL,
  `locality_village` varchar(255) DEFAULT NULL,
  `locality_panchayath` varchar(255) DEFAULT NULL,
  `locality_district` varchar(255) DEFAULT NULL,
  `locality_state` varchar(255) DEFAULT NULL,
  `locality_pin_code` varchar(255) DEFAULT NULL,
  `families_in_mahallu` varchar(255) DEFAULT NULL,
  `site_has_building` varchar(255) DEFAULT NULL,
  `status_of_current_building` varchar(255) DEFAULT NULL,
  `status_of_current_building_other` varchar(255) DEFAULT NULL,
  `requirement` varchar(255) DEFAULT NULL,
  `building_area_sq` varchar(255) DEFAULT NULL,
  `amount_requested` varchar(255) DEFAULT NULL,
  `legal_approvals_status` varchar(255) DEFAULT NULL,
  `permitted_type` varchar(255) DEFAULT NULL,
  `area` varchar(255) DEFAULT NULL,
  `additional_note` text DEFAULT NULL,
  `recommendation_name` varchar(255) DEFAULT NULL,
  `recommendation_organization` varchar(255) DEFAULT NULL,
  `recommendation_organization_other` varchar(255) DEFAULT NULL,
  `recommendation_phone` varchar(255) DEFAULT NULL,
  `recommendation_position` varchar(255) DEFAULT NULL,
  `status` varchar(255) NOT NULL DEFAULT \'Pending\',
  `rejected_reason` text DEFAULT NULL,
  `agency_number` varchar(255) DEFAULT NULL,
  `agency_name` varchar(255) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `is_pharmacy` varchar(255) DEFAULT NULL,
  `project_area` varchar(255) DEFAULT NULL,
  `num_beds` int(11) DEFAULT NULL,
  `house_name` text DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `hospital_clinic_applications_status_idx` (`status`),
  KEY `hospital_clinic_applications_created_at_idx` (`created_at`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci');
        DB::statement('CREATE TABLE `drinking_water_group_applications` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `applicant_name` varchar(255) NOT NULL,
  `contact_email` varchar(255) DEFAULT NULL,
  `contact_number_1` text DEFAULT NULL,
  `contact_number_2` text DEFAULT NULL,
  `place` text DEFAULT NULL,
  `post_office` text DEFAULT NULL,
  `village` text DEFAULT NULL,
  `panchayat` text DEFAULT NULL,
  `district` text DEFAULT NULL,
  `state` text DEFAULT NULL,
  `pin_code` text DEFAULT NULL,
  `submitted_before` varchar(255) DEFAULT NULL,
  `received_support_before` varchar(255) DEFAULT NULL,
  `financial_support_purpose` varchar(255) DEFAULT NULL,
  `locality_place` varchar(255) DEFAULT NULL,
  `locality_post` varchar(255) DEFAULT NULL,
  `locality_village` varchar(255) DEFAULT NULL,
  `locality_panchayath` varchar(255) DEFAULT NULL,
  `locality_district` varchar(255) DEFAULT NULL,
  `locality_state` varchar(255) DEFAULT NULL,
  `locality_pin_code` varchar(255) DEFAULT NULL,
  `amount_requested` varchar(255) DEFAULT NULL,
  `additional_note` text DEFAULT NULL,
  `recommendation_name` varchar(255) DEFAULT NULL,
  `recommendation_organization` varchar(255) DEFAULT NULL,
  `recommendation_organization_other` varchar(255) DEFAULT NULL,
  `recommendation_phone` varchar(255) DEFAULT NULL,
  `recommendation_position` varchar(255) DEFAULT NULL,
  `status` varchar(255) NOT NULL DEFAULT \'Pending\',
  `rejected_reason` text DEFAULT NULL,
  `agency_number` varchar(255) DEFAULT NULL,
  `agency_name` varchar(255) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `gender` varchar(255) DEFAULT NULL,
  `male_adults` int(11) DEFAULT NULL,
  `male_children` int(11) DEFAULT NULL,
  `female_adults` int(11) DEFAULT NULL,
  `female_children` int(11) DEFAULT NULL,
  `num_benefited_people` varchar(255) DEFAULT NULL,
  `land_owner_name` varchar(255) DEFAULT NULL,
  `land_owner_address` varchar(255) DEFAULT NULL,
  `land_owner_place` varchar(255) DEFAULT NULL,
  `land_owner_post` varchar(255) DEFAULT NULL,
  `land_owner_panchayath` varchar(255) DEFAULT NULL,
  `land_owner_district` varchar(255) DEFAULT NULL,
  `land_owner_mobile` varchar(255) DEFAULT NULL,
  `well_type` varchar(255) DEFAULT NULL,
  `well_depth` varchar(255) DEFAULT NULL,
  `legal_permissions` varchar(255) DEFAULT NULL,
  `beneficiaries` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `land_owner_pin` varchar(255) DEFAULT NULL,
  `land_owner_village` varchar(255) DEFAULT NULL,
  `land_owner_state` varchar(255) DEFAULT NULL,
  `permitted_type` varchar(255) DEFAULT NULL,
  `house_name` text DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `drinking_water_group_applications_status_idx` (`status`),
  KEY `drinking_water_group_applications_created_at_idx` (`created_at`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci');
        DB::statement('CREATE TABLE `drinking_water_individual_applications` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `applicant_name` varchar(255) NOT NULL,
  `contact_email` varchar(255) DEFAULT NULL,
  `contact_number_1` text DEFAULT NULL,
  `contact_number_2` text DEFAULT NULL,
  `place` text DEFAULT NULL,
  `post_office` text DEFAULT NULL,
  `village` text DEFAULT NULL,
  `panchayat` text DEFAULT NULL,
  `district` text DEFAULT NULL,
  `state` text DEFAULT NULL,
  `pin_code` text DEFAULT NULL,
  `submitted_before` varchar(255) DEFAULT NULL,
  `received_support_before` varchar(255) DEFAULT NULL,
  `financial_support_purpose` varchar(255) DEFAULT NULL,
  `locality_place` varchar(255) DEFAULT NULL,
  `locality_post` varchar(255) DEFAULT NULL,
  `locality_village` varchar(255) DEFAULT NULL,
  `locality_panchayath` varchar(255) DEFAULT NULL,
  `locality_district` varchar(255) DEFAULT NULL,
  `locality_state` varchar(255) DEFAULT NULL,
  `locality_pin_code` varchar(255) DEFAULT NULL,
  `amount_requested` varchar(255) DEFAULT NULL,
  `additional_note` text DEFAULT NULL,
  `recommendation_name` varchar(255) DEFAULT NULL,
  `recommendation_organization` varchar(255) DEFAULT NULL,
  `recommendation_organization_other` varchar(255) DEFAULT NULL,
  `recommendation_phone` varchar(255) DEFAULT NULL,
  `recommendation_position` varchar(255) DEFAULT NULL,
  `status` varchar(255) NOT NULL DEFAULT \'Pending\',
  `rejected_reason` text DEFAULT NULL,
  `agency_number` varchar(255) DEFAULT NULL,
  `agency_name` varchar(255) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `job` varchar(255) DEFAULT NULL,
  `monthly_income` varchar(255) DEFAULT NULL,
  `num_male_benefited` varchar(255) DEFAULT NULL,
  `num_female_benefited` varchar(255) DEFAULT NULL,
  `num_benefited_people` varchar(255) DEFAULT NULL,
  `land_owner_name` varchar(255) DEFAULT NULL,
  `land_owner_address` varchar(255) DEFAULT NULL,
  `land_owner_place` varchar(255) DEFAULT NULL,
  `land_owner_post` varchar(255) DEFAULT NULL,
  `land_owner_panchayath` varchar(255) DEFAULT NULL,
  `land_owner_district` varchar(255) DEFAULT NULL,
  `land_owner_mobile` varchar(255) DEFAULT NULL,
  `well_type` varchar(255) DEFAULT NULL,
  `well_depth` varchar(255) DEFAULT NULL,
  `well_diameter` varchar(255) DEFAULT NULL,
  `land_nature` varchar(255) DEFAULT NULL,
  `current_water_source` varchar(255) DEFAULT NULL,
  `need_pump` varchar(255) DEFAULT NULL,
  `well_for_agriculture` varchar(255) DEFAULT NULL,
  `gender` varchar(255) DEFAULT NULL,
  `beneficiaries` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `legal_permissions` varchar(255) DEFAULT NULL,
  `land_owner_pin` varchar(255) DEFAULT NULL,
  `land_owner_village` varchar(255) DEFAULT NULL,
  `land_owner_state` varchar(255) DEFAULT NULL,
  `permitted_type` varchar(255) DEFAULT NULL,
  `house_name` text DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `drinking_water_individual_applications_status_idx` (`status`),
  KEY `drinking_water_individual_applications_created_at_idx` (`created_at`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci');
        DB::statement('CREATE TABLE `general_applications` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `applicant_name` varchar(255) NOT NULL,
  `contact_email` varchar(255) DEFAULT NULL,
  `contact_number_1` text DEFAULT NULL,
  `contact_number_2` text DEFAULT NULL,
  `house_name` text DEFAULT NULL,
  `place` text DEFAULT NULL,
  `post_office` text DEFAULT NULL,
  `village` text DEFAULT NULL,
  `panchayat` text DEFAULT NULL,
  `district` text DEFAULT NULL,
  `state` text DEFAULT NULL,
  `pin_code` text DEFAULT NULL,
  `amount_requested` varchar(255) DEFAULT NULL,
  `additional_note` text DEFAULT NULL,
  `recommendation_name` varchar(255) DEFAULT NULL,
  `recommendation_organization` varchar(255) DEFAULT NULL,
  `recommendation_organization_other` varchar(255) DEFAULT NULL,
  `recommendation_phone` varchar(255) DEFAULT NULL,
  `recommendation_position` varchar(255) DEFAULT NULL,
  `status` varchar(255) NOT NULL DEFAULT \'Pending\',
  `rejected_reason` text DEFAULT NULL,
  `agency_number` varchar(255) DEFAULT NULL,
  `agency_name` varchar(255) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `application_type` varchar(255) DEFAULT \'Individual\',
  `organization_name` varchar(255) DEFAULT NULL,
  `unit` varchar(255) DEFAULT NULL,
  `age` varchar(255) DEFAULT NULL,
  `sex` varchar(255) DEFAULT NULL,
  `status_of_applicant` varchar(255) DEFAULT NULL,
  `education` varchar(255) DEFAULT NULL,
  `num_earning_members` int(11) DEFAULT NULL,
  `applying_for` varchar(255) DEFAULT NULL,
  `monthly_income_detail` int(11) DEFAULT NULL,
  `recommended_by` varchar(255) DEFAULT NULL,
  `recommended_phone` varchar(255) DEFAULT NULL,
  `office_application_type` varchar(255) DEFAULT NULL,
  `gender` varchar(255) DEFAULT NULL,
  `father_name` varchar(255) DEFAULT NULL,
  `mother_name` varchar(255) DEFAULT NULL,
  `married` varchar(255) DEFAULT NULL,
  `male_family_members` int(11) DEFAULT NULL,
  `female_family_members` int(11) DEFAULT NULL,
  `total_family_members` int(11) DEFAULT NULL,
  `occupation` varchar(255) DEFAULT NULL,
  `monthly_income` varchar(255) DEFAULT NULL,
  `other_income` varchar(255) DEFAULT NULL,
  `health_status` varchar(255) DEFAULT NULL,
  `accommodation_details` text DEFAULT NULL,
  `general_app_status` varchar(255) DEFAULT NULL,
  `office_app_type` varchar(255) DEFAULT NULL,
  `block` varchar(255) DEFAULT NULL,
  `ward` varchar(255) DEFAULT NULL,
  `panchayat_municipality_corporation` varchar(255) DEFAULT NULL,
  `locality_pin_code` varchar(255) DEFAULT NULL,
  `locality_place` varchar(255) DEFAULT NULL,
  `locality_village` varchar(255) DEFAULT NULL,
  `locality_post` varchar(255) DEFAULT NULL,
  `locality_panchayath` varchar(255) DEFAULT NULL,
  `locality_district` varchar(255) DEFAULT NULL,
  `locality_state` varchar(255) DEFAULT NULL,
  `submitted_before` varchar(255) DEFAULT NULL,
  `received_support_before` varchar(255) DEFAULT NULL,
  `financial_support_purpose` varchar(255) DEFAULT NULL,
  `permitted_type` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `general_applications_status_idx` (`status`),
  KEY `general_applications_created_at_idx` (`created_at`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci');
        DB::statement('CREATE TABLE `education_center_applications` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `applicant_name` varchar(255) NOT NULL,
  `committee_name` varchar(255) DEFAULT NULL,
  `reg_number` varchar(255) DEFAULT NULL,
  `year` varchar(255) DEFAULT NULL,
  `contact_email` varchar(255) DEFAULT NULL,
  `contact_number_1` text DEFAULT NULL,
  `contact_number_2` text DEFAULT NULL,
  `place` text DEFAULT NULL,
  `post_office` text DEFAULT NULL,
  `village` text DEFAULT NULL,
  `panchayat` text DEFAULT NULL,
  `district` text DEFAULT NULL,
  `state` text DEFAULT NULL,
  `pin_code` text DEFAULT NULL,
  `submitted_before` varchar(255) DEFAULT NULL,
  `received_support_before` varchar(255) DEFAULT NULL,
  `financial_support_purpose` varchar(255) DEFAULT NULL,
  `mahallu_name` varchar(255) DEFAULT NULL,
  `locality_place` varchar(255) DEFAULT NULL,
  `locality_post` varchar(255) DEFAULT NULL,
  `locality_village` varchar(255) DEFAULT NULL,
  `locality_panchayath` varchar(255) DEFAULT NULL,
  `locality_district` varchar(255) DEFAULT NULL,
  `locality_state` varchar(255) DEFAULT NULL,
  `locality_pin_code` varchar(255) DEFAULT NULL,
  `families_in_mahallu` varchar(255) DEFAULT NULL,
  `site_has_building` varchar(255) DEFAULT NULL,
  `status_of_current_building` varchar(255) DEFAULT NULL,
  `status_of_current_building_other` varchar(255) DEFAULT NULL,
  `students_boys` int(11) DEFAULT NULL,
  `students_girls` int(11) DEFAULT NULL,
  `total_students` int(11) DEFAULT NULL,
  `education_center_nearby` varchar(255) DEFAULT NULL,
  `distance_education_center` varchar(255) DEFAULT NULL,
  `syllabus` varchar(255) DEFAULT NULL,
  `project_type` varchar(255) DEFAULT NULL,
  `requirement` varchar(255) DEFAULT NULL,
  `building_area_sq` varchar(255) DEFAULT NULL,
  `land_area_sq` varchar(255) DEFAULT NULL,
  `num_classrooms` varchar(255) DEFAULT NULL,
  `num_students` varchar(255) DEFAULT NULL,
  `amount_requested` varchar(255) DEFAULT NULL,
  `legal_approvals_status` varchar(255) DEFAULT NULL,
  `permitted_type` varchar(255) DEFAULT NULL,
  `area` varchar(255) DEFAULT NULL,
  `additional_note` text DEFAULT NULL,
  `recommendation_name` varchar(255) DEFAULT NULL,
  `recommendation_organization` varchar(255) DEFAULT NULL,
  `recommendation_organization_other` varchar(255) DEFAULT NULL,
  `recommendation_phone` varchar(255) DEFAULT NULL,
  `recommendation_position` varchar(255) DEFAULT NULL,
  `status` varchar(255) NOT NULL DEFAULT \'Pending\',
  `rejected_reason` text DEFAULT NULL,
  `agency_number` varchar(255) DEFAULT NULL,
  `agency_name` varchar(255) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `house_name` text DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `education_center_applications_status_idx` (`status`),
  KEY `education_center_applications_created_at_idx` (`created_at`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci');
        DB::statement('CREATE TABLE `cultural_center_applications` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `applicant_name` varchar(255) DEFAULT NULL,
  `committee_name` varchar(255) DEFAULT NULL,
  `reg_number` varchar(255) DEFAULT NULL,
  `year` varchar(255) DEFAULT NULL,
  `pin_code` varchar(255) DEFAULT NULL,
  `place` varchar(255) DEFAULT NULL,
  `village` varchar(255) DEFAULT NULL,
  `post_office` varchar(255) DEFAULT NULL,
  `panchayat` varchar(255) DEFAULT NULL,
  `district` varchar(255) DEFAULT NULL,
  `state` varchar(255) DEFAULT NULL,
  `contact_number_1` varchar(255) DEFAULT NULL,
  `contact_number_2` varchar(255) DEFAULT NULL,
  `submitted_before` varchar(255) DEFAULT NULL,
  `received_support_before` varchar(255) DEFAULT NULL,
  `financial_support_purpose` varchar(255) DEFAULT NULL,
  `mahallu_name` varchar(255) DEFAULT NULL,
  `locality_pin_code` varchar(255) DEFAULT NULL,
  `locality_place` varchar(255) DEFAULT NULL,
  `locality_village` varchar(255) DEFAULT NULL,
  `locality_post` varchar(255) DEFAULT NULL,
  `locality_panchayath` varchar(255) DEFAULT NULL,
  `locality_district` varchar(255) DEFAULT NULL,
  `locality_state` varchar(255) DEFAULT NULL,
  `families_in_mahallu` varchar(255) DEFAULT NULL,
  `site_has_building` varchar(255) DEFAULT NULL,
  `status_of_current_building` varchar(255) DEFAULT NULL,
  `status_of_current_building_other` varchar(255) DEFAULT NULL,
  `cultural_center_nearby` varchar(255) DEFAULT NULL,
  `distance_cultural_centre` varchar(255) DEFAULT NULL,
  `benefited_households` varchar(255) DEFAULT NULL,
  `project_type` varchar(255) DEFAULT NULL,
  `requirement` varchar(255) DEFAULT NULL,
  `building_area_sq` varchar(255) DEFAULT NULL,
  `land_area_sq` varchar(255) DEFAULT NULL,
  `num_beneficiaries` varchar(255) DEFAULT NULL,
  `amount_requested` varchar(255) DEFAULT NULL,
  `legal_approvals_status` varchar(255) DEFAULT NULL,
  `permitted_type` varchar(255) DEFAULT NULL,
  `area` varchar(255) DEFAULT NULL,
  `additional_note` text DEFAULT NULL,
  `recommendation_name` varchar(255) DEFAULT NULL,
  `recommendation_organization` varchar(255) DEFAULT NULL,
  `recommendation_organization_other` varchar(255) DEFAULT NULL,
  `recommendation_phone` varchar(255) DEFAULT NULL,
  `recommendation_position` varchar(255) DEFAULT NULL,
  `contact_email` varchar(255) DEFAULT NULL,
  `status` varchar(255) NOT NULL DEFAULT \'Pending\',
  `rejected_reason` text DEFAULT NULL,
  `agency_number` varchar(255) DEFAULT NULL,
  `agency_name` varchar(255) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `house_name` text DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `cultural_center_applications_status_idx` (`status`),
  KEY `cultural_center_applications_created_at_idx` (`created_at`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci');
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('cultural_center_applications');
        Schema::dropIfExists('education_center_applications');
        Schema::dropIfExists('general_applications');
        Schema::dropIfExists('drinking_water_individual_applications');
        Schema::dropIfExists('drinking_water_group_applications');
        Schema::dropIfExists('hospital_clinic_applications');
        Schema::dropIfExists('shop_other_applications');
        Schema::dropIfExists('house_applications');
        Schema::dropIfExists('family_aid_applications');
        Schema::dropIfExists('differently_abled_applications');
        Schema::dropIfExists('orphan_care_applications');
        Schema::dropIfExists('applications');
    }
};
