<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    /**
     * Reorder columns across all application tables to match application form field model.
     */
    public function up(): void
    {
        $tablesConfig = [
        'cultural_center_applications' => [
            'applicant_name',
            'committee_name',
            'reg_number',
            'year',
            'pin_code',
            'location',
            'village',
            'post',
            'panchayath',
            'district',
            'state',
            'contact_number_1',
            'contact_number_2',
            'submitted_before',
            'received_support_before',
            'financial_support_purpose',
            'mahallu_name',
            'locality_pin_code',
            'locality_location',
            'locality_village',
            'locality_post',
            'locality_panchayath',
            'locality_district',
            'locality_state',
            'families_in_mahallu',
            'site_has_building',
            'status_of_current_building',
            'status_of_current_building_other',
            'cultural_center_nearby',
            'distance_cultural_centre',
            'benefited_households',
            'project_type',
            'requirement',
            'building_area_sq',
            'land_area_sq',
            'amount_requested',
            'legal_approvals_status',
            'permitted_type',
            'area',
            'details',
            'recommendation_name',
            'recommendation_organization',
            'recommendation_organization_other',
            'recommendation_phone',
            'recommendation_position'
        ],
        'differently_abled_applications' => [
            'amount_requested',
            'applicant_name',
            'father_name',
            'fathers_father',
            'mother_name',
            'gender',
            'aadhar_number',
            'dob',
            'age',
            'marital_status',
            'guardian_name',
            'guardian_relation',
            'male_members',
            'female_members',
            'total_members',
            'people_with_disabilities',
            'monthly_income',
            'monthly_cost',
            'income_source',
            'studying_institution',
            'not_studying_reason',
            'health_status',
            'disability_type',
            'disability_percentage',
            'disability_date',
            'disability_level',
            'other_help',
            'description',
            'accommodation',
            'details',
            'cluster_id',
            'agency_number',
            'recommendation_name',
            'recommendation_organization',
            'recommendation_organization_other',
            'recommendation_phone',
            'recommendation_position'
        ],
        'drinking_water_group_applications' => [
            'applicant_name',
            'father_name',
            'mother_name',
            'fathers_father',
            'gender',
            'dob',
            'age',
            'aadhar_number',
            'pin',
            'location',
            'address',
            'village',
            'post',
            'panchayath',
            'district',
            'state',
            'contact_number_1',
            'contact_number_2',
            'male_adults',
            'male_children',
            'female_adults',
            'female_children',
            'num_benefited_people',
            'land_owner_name',
            'land_owner_address',
            'land_owner_place',
            'land_owner_post',
            'land_owner_panchayath',
            'land_owner_district',
            'land_owner_mobile',
            'well_type',
            'well_depth',
            'legal_permissions',
            'amount_requested',
            'details',
            'recommendation_name',
            'recommendation_organization',
            'recommendation_organization_other',
            'recommendation_phone',
            'recommendation_position'
        ],
        'drinking_water_individual_applications' => [
            'applicant_name',
            'pin',
            'location',
            'address',
            'village',
            'post',
            'panchayath',
            'district',
            'state',
            'contact_number_1',
            'contact_number_2',
            'job',
            'monthly_income',
            'num_male_benefited',
            'num_female_benefited',
            'num_benefited_people',
            'land_owner_name',
            'land_owner_address',
            'land_owner_place',
            'land_owner_post',
            'land_owner_panchayath',
            'land_owner_district',
            'land_owner_mobile',
            'well_type',
            'well_depth',
            'well_diameter',
            'amount_requested',
            'land_nature',
            'current_water_source',
            'need_pump',
            'well_for_agriculture',
            'details',
            'recommendation_name',
            'recommendation_organization',
            'recommendation_organization_other',
            'recommendation_phone',
            'recommendation_position'
        ],
        'education_center_applications' => [
            'applicant_name',
            'committee_name',
            'reg_number',
            'year',
            'pin_code',
            'location',
            'village',
            'post',
            'panchayath',
            'district',
            'state',
            'contact_number_1',
            'contact_number_2',
            'submitted_before',
            'received_support_before',
            'financial_support_purpose',
            'mahallu_name',
            'locality_pin_code',
            'locality_location',
            'locality_village',
            'locality_post',
            'locality_panchayath',
            'locality_district',
            'locality_state',
            'families_in_mahallu',
            'site_has_building',
            'status_of_current_building',
            'status_of_current_building_other',
            'students_boys',
            'students_girls',
            'total_students',
            'education_center_nearby',
            'syllabus',
            'distance_education_center',
            'project_type',
            'requirement',
            'building_area_sq',
            'land_area_sq',
            'num_classrooms',
            'num_students',
            'amount_requested',
            'legal_approvals_status',
            'permitted_type',
            'area',
            'details',
            'recommendation_name',
            'recommendation_organization',
            'recommendation_organization_other',
            'recommendation_phone',
            'recommendation_position'
        ],
        'family_aid_applications' => [
            'amount_requested',
            'applicant_name',
            'father_name',
            'mother_name',
            'fathers_father',
            'dob',
            'age',
            'aadhar_number',
            'house_name',
            'pin_code',
            'place',
            'village',
            'post_office',
            'panchayat',
            'district',
            'state',
            'mobile_1',
            'mobile_2',
            'children_total',
            'children_male',
            'children_female',
            'nri_status',
            'occupation',
            'monthly_income',
            'other_income_sources',
            'health_status',
            'disability_status',
            'routine_treatment_explanation',
            'chronic_patients_description',
            'residence_info',
            'own_house_condition',
            'own_place_status',
            'own_place_size',
            'sequel_status',
            'welfare_assistance_areas',
            'details',
            'cluster_id',
            'agency_number',
            'recommendation_name',
            'recommendation_organization',
            'recommendation_organization_other',
            'recommendation_phone',
            'recommendation_position'
        ],
        'general_applications' => [
            'application_type',
            'organization_name',
            'unit',
            'applicant_name',
            'age',
            'sex',
            'status_of_applicant',
            'education',
            'num_male_family',
            'num_female_family',
            'num_total_family',
            'num_earning_members',
            'average_monthly_income',
            'applying_for',
            'monthly_income_detail',
            'recommended_by',
            'recommended_phone',
            'office_application_type',
            'details',
            'amount_requested',
            'recommendation_name',
            'recommendation_organization',
            'recommendation_organization_other',
            'recommendation_phone',
            'recommendation_position'
        ],
        'hospital_clinic_applications' => [
            'applicant_name',
            'committee_name',
            'reg_number',
            'year',
            'pin_code',
            'place',
            'village',
            'post',
            'panchayath',
            'district',
            'state',
            'contact_number_1',
            'contact_number_2',
            'mahallu_name',
            'locality_pin_code',
            'locality_location',
            'locality_village',
            'locality_post',
            'locality_panchayath',
            'locality_district',
            'locality_state',
            'families_in_mahallu',
            'site_has_building',
            'status_of_current_building',
            'status_of_current_building_other',
            'requirement',
            'building_area_sq',
            'area',
            'amount_requested',
            'is_pharmacy',
            'legal_approvals_status',
            'permitted_type',
            'project_area',
            'num_beds',
            'details',
            'recommendation_name',
            'recommendation_organization',
            'recommendation_organization_other',
            'recommendation_phone',
            'recommendation_position'
        ],
        'house_applications' => [
            'applicant_name',
            'age',
            'father_name',
            'mother_name',
            'house_name',
            'pin_code',
            'place',
            'village',
            'post',
            'panchayath',
            'district',
            'state',
            'gender',
            'contact_number_1',
            'contact_number_2',
            'education',
            'married',
            'num_children',
            'num_male_children',
            'num_female_children',
            'has_occupation',
            'monthly_income',
            'other_income',
            'health_status',
            'daily_treatment_explanation',
            'accommodation_details',
            'own_place',
            'own_place_details',
            'land_type',
            'desired_model',
            'building_area_sq',
            'amount_requested',
            'legal_approvals_status',
            'intended_house_form',
            'office_build_house',
            'details',
            'recommendation_name',
            'recommendation_organization',
            'recommendation_organization_other',
            'recommendation_phone',
            'recommendation_position'
        ],
        'orphan_care_applications' => [
            'amount_requested',
            'applicant_name',
            'gender',
            'father_name',
            'grandfather_name',
            'student_photo',
            'mother_name',
            'mothers_father_name',
            'dob',
            'age',
            'aadhar_number',
            'guardian_name',
            'guardian_relation',
            'father_death_date',
            'father_death_cause',
            'mother_alive_status',
            'mother_remarried_status',
            'mother_death_date',
            'mother_death_cause',
            'siblings_male',
            'siblings_female',
            'siblings_total',
            'current_beneficiaries',
            'monthly_income',
            'monthly_expense',
            'sponsorship_details',
            'house_type',
            'school_name',
            'school_class',
            'madrassa_name',
            'madrassa_class',
            'not_studying_reason',
            'health_status',
            'details',
            'recommender_name',
            'recommender_org',
            'recommender_phone',
            'recommender_position',
            'cluster_id',
            'agency_number',
            'agency_name',
            'application_date',
            'recommendation_name',
            'recommendation_organization',
            'recommendation_organization_other',
            'recommendation_phone',
            'recommendation_position'
        ],
        'shop_other_applications' => [
            'applicant_name',
            'committee_name',
            'reg_number',
            'year',
            'pin_code',
            'place',
            'village',
            'post',
            'panchayath',
            'district',
            'state',
            'contact_number_1',
            'contact_number_2',
            'mahallu_name',
            'locality_pin_code',
            'locality_location',
            'locality_village',
            'locality_post',
            'locality_panchayath',
            'locality_district',
            'locality_state',
            'site_has_building',
            'status_of_current_building',
            'status_of_current_building_other',
            'building_area_sq',
            'area',
            'amount_requested',
            'families_in_mahallu',
            'legal_approvals_status',
            'permitted_type',
            'project_area',
            'num_rooms',
            'office_shop',
            'details',
            'recommendation_name',
            'recommendation_organization',
            'recommendation_organization_other',
            'recommendation_phone',
        ]
    ];

    if (DB::getDriverName() !== 'mysql') {
        return;
    }

        foreach ($tablesConfig as $tableName => $desiredOrder) {
            if (!DB::getSchemaBuilder()->hasTable($tableName)) {
                continue;
            }

            $columns = DB::select("SHOW FULL COLUMNS FROM `{$tableName}`");
            $colMap = [];
            foreach ($columns as $col) {
                $colMap[$col->Field] = $col;
            }

            // System & meta columns that should be ordered gracefully at the end if not in desiredOrder
            $standardTail = [
                'status', 'rejected_reason', 'cluster_id', 'agency_number', 'agency_name', 
                'application_date', 'whatsapp_number', 'current_beneficiaries',
                'project_id', 'created_at', 'updated_at'
            ];

            $orderedList = [];
            foreach ($desiredOrder as $col) {
                if (isset($colMap[$col]) && !in_array($col, $orderedList)) {
                    $orderedList[] = $col;
                }
            }

            foreach ($standardTail as $col) {
                if (isset($colMap[$col]) && !in_array($col, $orderedList)) {
                    $orderedList[] = $col;
                }
            }

            foreach ($colMap as $field => $col) {
                if ($field !== 'id' && !in_array($field, $orderedList)) {
                    $orderedList[] = $field;
                }
            }

            $prev = 'id';
            foreach ($orderedList as $colName) {
                if (!isset($colMap[$colName])) continue;

                $col = $colMap[$colName];
                $type = $col->Type;
                $null = $col->Null === 'YES' ? 'NULL' : 'NOT NULL';
                $default = '';
                if ($col->Default !== null) {
                    $default = "DEFAULT '" . addslashes($col->Default) . "'";
                } elseif ($col->Null === 'YES') {
                    $default = 'DEFAULT NULL';
                }
                $extra = $col->Extra ? $col->Extra : '';
                $collation = $col->Collation ? "CHARACTER SET utf8mb4 COLLATE {$col->Collation}" : '';

                $sql = "ALTER TABLE `{$tableName}` MODIFY COLUMN `{$colName}` {$type} {$collation} {$null} {$default} {$extra} AFTER `{$prev}`";

                try {
                    DB::statement($sql);
                } catch (\Exception $e) {
                    // Ignore column reorder error for individual column if constraint blocks it
                }

                $prev = $colName;
            }
        }
    }

    public function down(): void
    {
    }
};
